const CONFIRMATION_TEXT = Object.freeze({
  PLOT_MERGE: "MERGE PLOTS IRREVERSIBLY",
  BUYBACK: "COMPLETE BUYBACK IRREVERSIBLY",
  CANCEL: "CANCEL BOOKING IRREVERSIBLY",
});

module.exports = { CONFIRMATION_TEXT };
