const { Plot } = require("./plot.model");

const STATUS_TRANSITIONS = {
  [Plot.STATUS.AVAILABLE]: [Plot.STATUS.RESERVED, Plot.STATUS.BOOKED, Plot.STATUS.CANCELLED, Plot.STATUS.MERGED],
  [Plot.STATUS.RESERVED]: [Plot.STATUS.AVAILABLE, Plot.STATUS.BOOKED, Plot.STATUS.CANCELLED, Plot.STATUS.MERGED],
  [Plot.STATUS.BOOKED]: [Plot.STATUS.ALLOTTED, Plot.STATUS.AVAILABLE, Plot.STATUS.CANCELLED, Plot.STATUS.MERGED],
  [Plot.STATUS.ALLOTTED]: [Plot.STATUS.SOLD, Plot.STATUS.TRANSFERRED, Plot.STATUS.POSSESSED, Plot.STATUS.UNDER_CONSTRUCTION, Plot.STATUS.CANCELLED, Plot.STATUS.AVAILABLE, Plot.STATUS.MERGED],
  [Plot.STATUS.SOLD]: [Plot.STATUS.TRANSFERRED, Plot.STATUS.POSSESSED, Plot.STATUS.UNDER_CONSTRUCTION],
  [Plot.STATUS.TRANSFERRED]: [Plot.STATUS.TRANSFERRED, Plot.STATUS.POSSESSED, Plot.STATUS.UNDER_CONSTRUCTION],
  [Plot.STATUS.CANCELLED]: [Plot.STATUS.AVAILABLE],
  [Plot.STATUS.POSSESSED]: [Plot.STATUS.UNDER_CONSTRUCTION, Plot.STATUS.CONSTRUCTED],
  [Plot.STATUS.UNDER_CONSTRUCTION]: [Plot.STATUS.CONSTRUCTED],
  [Plot.STATUS.CONSTRUCTED]: [],
  [Plot.STATUS.MERGED]: [],
  [Plot.STATUS.BOUGHT_BACK]: [Plot.STATUS.AVAILABLE],
};

const canTransition = (from, to) => from === to || STATUS_TRANSITIONS[from]?.includes(to);

module.exports = { STATUS_TRANSITIONS, canTransition };