const QRCode = require("qrcode");
const PDFDocument = require("pdfkit");
const NocApplication = require("./noc.model");
const { Plot } = require("../properties/plot.model");
const { Installment } = require("../bookings/booking.model");
const Member = require("../members/member.model");
const { db } = require("../../config/db");
const NumberingRule = require("../administration/numberingRule.model");
const { createAuditLog, AuditLog } = require("../administration/auditLog.model");
const ApiError = require("../../utils/ApiError");
const NotificationService = require("../notifications/service");
const InvoiceService = require("../invoices/service");

const PUBLIC_BASE_URL = process.env.PUBLIC_API_URL || "http://localhost:5000";
const stagesUpdate = (stages, name, actor, status, remarks) => stages.map((stage) => stage.stage === name ? { ...stage, status, approver: actor, actedAt: new Date().toISOString(), remarks: remarks || null } : stage);

class NocService {
  static async enrich(noc) { const [member, plot] = await Promise.all([Member.findById(noc.member), Plot.findById(noc.plot)]); return { ...noc, memberRef: member, plotRef: plot }; }
  static async create(data, req) { if (!(await Member.findById(data.member))) throw new ApiError(400, "Member not found"); if (!(await Plot.findById(data.plot))) throw new ApiError(400, "Plot not found"); const noc = await NocApplication.create({ ...data, feeAmount: Number(data.feeAmount) }, req.user._id); await createAuditLog({ req, entityType: "NocApplication", entityId: noc._id, action: AuditLog.ACTIONS.CREATE, changes: { after: noc } }); return this.enrich(noc); }
  static async get(id) { const noc = await NocApplication.findById(id); if (!noc) throw new ApiError(404, "NOC application not found"); return this.enrich(noc); }
  static async list({ status, page = 1, limit = 20 }) { const all = await NocApplication.find(status ? { status } : {}, { sort: { createdAt: -1 } }); const p = Number(page) || 1; const l = Number(limit) || 20; return { data: await Promise.all(all.slice((p - 1) * l, p * l).map((noc) => this.enrich(noc))), pagination: { page: p, limit: l, total: all.length, pages: Math.ceil(all.length / l) } }; }
  static async verify(id, req) { const noc = await NocApplication.findById(id); if (!noc) throw new ApiError(404, "NOC application not found"); const plot = await Plot.findById(noc.plot); if (!plot || plot.currentOwner !== noc.member) throw new ApiError(409, "Member is not the current plot owner"); const stages = stagesUpdate(noc.approvalStages, "Verification", req.user._id, "Completed", "Identity and ownership verified"); const installments = await Installment.find({ member: noc.member }); const dues = installments.filter((item) => item.plot === noc.plot && Number(item.balance) > 0).reduce((sum, item) => sum + Number(item.balance), 0); await NocApplication.update(id, { status: dues > 0 ? NocApplication.STATUS.DUES_PENDING : NocApplication.STATUS.UNDER_VERIFICATION, duesCleared: dues === 0, outstandingDues: dues, approvalStages: stages }); return this.get(id); }
  static async clearDues(id, req) { const noc = await NocApplication.findById(id); if (!noc) throw new ApiError(404, "NOC application not found"); const installments = await Installment.find({ member: noc.member }); const dues = installments.filter((item) => item.plot === noc.plot && Number(item.balance) > 0).reduce((sum, item) => sum + Number(item.balance), 0); if (dues > 0) throw new ApiError(409, `Outstanding dues of ${dues} block NOC issuance`); await NocApplication.update(id, { status: NocApplication.STATUS.UNDER_VERIFICATION, duesCleared: true, outstandingDues: 0, approvalStages: stagesUpdate(noc.approvalStages, "Dues", req.user._id, "Completed", "Dues cleared") }); return this.get(id); }
  static async payFee(id, req) { const noc = await NocApplication.findById(id); if (!noc) throw new ApiError(404, "NOC application not found"); if (![NocApplication.STATUS.UNDER_VERIFICATION, NocApplication.STATUS.DUES_PENDING].includes(noc.status)) throw new ApiError(409, "NOC is not ready for fee payment"); await NocApplication.update(id, { feePaid: true, feePaidAt: new Date().toISOString(), status: NocApplication.STATUS.UNDER_VERIFICATION, approvalStages: stagesUpdate(noc.approvalStages, "Fee", req.user._id, "Completed", "NOC fee paid") }); return this.get(id); }
  static async approve(id, req) { const noc = await NocApplication.findById(id); if (!noc) throw new ApiError(404, "NOC application not found"); if (!noc.feePaid || !noc.duesCleared) throw new ApiError(409, "NOC dues and fee must be cleared before approval"); await NocApplication.update(id, { status: NocApplication.STATUS.APPROVED, approvalStages: stagesUpdate(noc.approvalStages, "Approval", req.user._id, "Completed", "Approved") }); await NotificationService.safeNotifyMember(noc.member, { title: "NOC application approved", message: "Your NOC application has been approved and is ready for issuance.", relatedEntityType: "NocApplication", relatedEntityId: id, eventType: "noc.approved", eventKey: `noc-approved:${id}` }); return this.get(id); }
  static async issue(id, req) { const noc = await NocApplication.findById(id); if (!noc) throw new ApiError(404, "NOC application not found"); if (noc.status !== NocApplication.STATUS.APPROVED) throw new ApiError(409, "Only approved NOCs can be issued"); const issuedNocNumber = await NumberingRule.getNextNumber("noc"); const token = NocApplication.createToken(); await NocApplication.update(id, { status: NocApplication.STATUS.ISSUED, issuedNocNumber, issuedDate: new Date().toISOString(), qrVerificationToken: token, approvalStages: stagesUpdate(noc.approvalStages, "Issue", req.user._id, "Completed", "NOC issued") }); await NotificationService.safeNotifyMember(noc.member, { title: "NOC issued", message: `Your NOC ${issuedNocNumber} has been issued.`, relatedEntityType: "NocApplication", relatedEntityId: id, eventType: "noc.issued", eventKey: `noc-issued:${id}` }); const issued = await this.get(id); await InvoiceService.safeRegisterInvoice("NOC", issued, { fileUrl: `/api/nocs/${id}/certificate.pdf`, createdBy: req.user._id }); return issued; }
  static async publicVerify(token) { const noc = await NocApplication.findByToken(token); if (!noc || noc.status !== NocApplication.STATUS.ISSUED) throw new ApiError(404, "NOC verification record not found"); const [plot, member] = await Promise.all([Plot.findById(noc.plot), Member.findById(noc.member)]); return { valid: true, issuedNocNumber: noc.issuedNocNumber, nocType: noc.nocType, status: noc.status, issuedDate: noc.issuedDate, plotNumber: plot?.plotNumber || null, memberName: member?.name || null }; }
  static async certificate(id) { const noc = await NocApplication.findById(id); if (!noc || noc.status !== NocApplication.STATUS.ISSUED) throw new ApiError(409, "NOC must be issued before certificate download"); const full = await this.get(id); const qrData = `${PUBLIC_BASE_URL}/api/nocs/verify/${noc.qrVerificationToken}`; const qr = await QRCode.toBuffer(qrData, { width: 180, margin: 1 }); return new Promise((resolve) => { const chunks = []; const pdf = new PDFDocument({ margin: 50 }); pdf.on("data", (chunk) => chunks.push(chunk)); pdf.on("end", () => resolve({ noc: full, buffer: Buffer.concat(chunks) })); pdf.fontSize(20).text("Housing Society NOC Certificate", { align: "center" }).moveDown().fontSize(12).text(`NOC Number: ${noc.issuedNocNumber}`).text(`Type: ${noc.nocType}`).text(`Member: ${full.memberRef?.name || noc.member}`).text(`Plot: ${full.plotRef?.plotNumber || noc.plot}`).text(`Issued: ${new Date(noc.issuedDate).toLocaleString()}`).moveDown().text("Scan to verify this NOC:").image(qr, { fit: [180, 180], align: "center" }).end(); }); }
}
module.exports = NocService;