const PDFDocument = require("pdfkit");
const { ConstructionApplication, SiteInspection } = require("./construction.model");
const { Plot } = require("../properties/plot.model");
const Member = require("../members/member.model");
const { canTransition } = require("../properties/stateMachine");
const { createAuditLog, AuditLog } = require("../administration/auditLog.model");
const ApiError = require("../../utils/ApiError");
const InvoiceService = require("../invoices/service");

const enrich = async (application) => { const [member, plot, inspections] = await Promise.all([Member.findById(application.member), Plot.findById(application.plot), SiteInspection.find({ application: application._id }, { sort: { date: 1, createdAt: 1 } })]); return { ...application, memberRef: member, plotRef: plot, inspections }; };
const allInspectionsPassed = (inspections) => inspections.length > 0 && inspections.every((inspection) => !inspection.violations?.length && !inspection.correctiveActionsRequired && !inspection.reinspectionRequired);

class ConstructionService {
  static async list({ status, page = 1, limit = 20 }) { const all = await ConstructionApplication.find(status ? { status } : {}, { sort: { createdAt: -1 } }); const p = Number(page) || 1; const l = Number(limit) || 20; return { data: await Promise.all(all.slice((p - 1) * l, p * l).map(enrich)), pagination: { page: p, limit: l, total: all.length, pages: Math.ceil(all.length / l) } }; }
  static async get(id) { const application = await ConstructionApplication.findById(id); if (!application) throw new ApiError(404, "Construction application not found"); return enrich(application); }
  static async create(data, req) { if (!(await Member.findById(data.member))) throw new ApiError(400, "Member not found"); const plot = await Plot.findById(data.plot); if (!plot) throw new ApiError(400, "Plot not found"); if (plot.currentOwner !== data.member) throw new ApiError(409, "Member is not the current plot owner"); const application = await ConstructionApplication.create({ ...data, fees: Number(data.fees) }, req.user._id); if (plot.status !== Plot.STATUS.UNDER_CONSTRUCTION && canTransition(plot.status, Plot.STATUS.UNDER_CONSTRUCTION)) await Plot.update(plot._id, { status: Plot.STATUS.UNDER_CONSTRUCTION }); await createAuditLog({ req, entityType: "ConstructionApplication", entityId: application._id, action: AuditLog.ACTIONS.CREATE, changes: { after: application } }); return this.get(application._id); }
  static async review(id, req) { const application = await ConstructionApplication.findById(id); if (!application) throw new ApiError(404, "Construction application not found"); if (application.status !== ConstructionApplication.STATUS.APPLIED) throw new ApiError(409, "Only applied construction requests can enter review"); await ConstructionApplication.update(id, { status: ConstructionApplication.STATUS.UNDER_REVIEW, reviewStatus: "UnderReview", reviewedBy: req.user._id, reviewedAt: new Date().toISOString() }); return this.get(id); }
  static async addInspection(id, data, req) { const application = await ConstructionApplication.findById(id); if (!application) throw new ApiError(404, "Construction application not found"); const inspection = await SiteInspection.create({ application: id, inspectorUser: req.user._id, date: data.date || new Date().toISOString(), ...data }); await createAuditLog({ req, entityType: "SiteInspection", entityId: inspection._id, action: AuditLog.ACTIONS.CREATE, changes: { after: inspection } }); return this.get(id); }
  static async updateInspection(id, data, req) { const inspection = await SiteInspection.findById(id); if (!inspection) throw new ApiError(404, "Site inspection not found"); await SiteInspection.update(id, data); await createAuditLog({ req, entityType: "SiteInspection", entityId: id, action: AuditLog.ACTIONS.UPDATE, changes: { before: inspection, after: data } }); return SiteInspection.findById(id); }
  static async approve(id, req) { const application = await ConstructionApplication.findById(id); if (!application) throw new ApiError(404, "Construction application not found"); if (application.status !== ConstructionApplication.STATUS.UNDER_REVIEW) throw new ApiError(409, "Construction application must be under review"); const inspections = await SiteInspection.find({ application: id }, { sort: { date: 1, createdAt: 1 } }); if (!allInspectionsPassed(inspections)) throw new ApiError(409, "All inspections must pass and corrective actions must be complete before approval"); const plot = await Plot.findById(application.plot); if (!canTransition(plot.status, Plot.STATUS.CONSTRUCTED)) throw new ApiError(409, `Plot cannot move from ${plot.status} to Constructed`); await Plot.update(plot._id, { status: Plot.STATUS.CONSTRUCTED }); await ConstructionApplication.update(id, { status: ConstructionApplication.STATUS.APPROVED, reviewStatus: "Approved", approvedBy: req.user._id, approvedAt: new Date().toISOString(), completionCertificateUrl: `/api/construction/${id}/completion-certificate.pdf` }); await createAuditLog({ req, entityType: "ConstructionApplication", entityId: id, action: AuditLog.ACTIONS.APPROVE, changes: { before: application, after: { status: ConstructionApplication.STATUS.APPROVED, plotStatus: Plot.STATUS.CONSTRUCTED } } }); const approved = await this.get(id); await InvoiceService.safeRegisterInvoice("Construction", approved, { fileUrl: approved.completionCertificateUrl || `/api/construction/${id}/completion-certificate.pdf`, createdBy: req.user._id }); return approved; }
  static async reject(id, remarks, req) { const application = await ConstructionApplication.findById(id); if (!application) throw new ApiError(404, "Construction application not found"); await ConstructionApplication.update(id, { status: ConstructionApplication.STATUS.REJECTED, rejectionRemarks: remarks }); await createAuditLog({ req, entityType: "ConstructionApplication", entityId: id, action: AuditLog.ACTIONS.REJECT, changes: { before: application, after: { status: ConstructionApplication.STATUS.REJECTED, remarks } } }); return this.get(id); }
  static async certificate(id) { const application = await this.get(id); if (application.status !== ConstructionApplication.STATUS.APPROVED) throw new ApiError(409, "Construction application must be approved before certificate download"); return new Promise((resolve) => { const chunks = []; const pdf = new PDFDocument({ margin: 50 }); pdf.on("data", (chunk) => chunks.push(chunk)); pdf.on("end", () => resolve({ application, buffer: Buffer.concat(chunks) })); pdf.fontSize(20).text("Housing Society Completion Certificate", { align: "center" }).moveDown().fontSize(12).text(`Member: ${application.memberRef?.name || application.member}`).text(`Plot: ${application.plotRef?.plotNumber || application.plot}`).text(`Application type: ${application.applicationType}`).text(`Approved: ${new Date(application.approvedAt).toLocaleString()}`).moveDown().text("Construction works have passed site inspection and are certified complete.").end(); }); }
}
module.exports = ConstructionService;