const PDFDocument = require("pdfkit");
const PossessionApplication = require("./possession.model");
const { Plot } = require("../properties/plot.model");
const { Installment } = require("../bookings/booking.model");
const Member = require("../members/member.model");
const { Plot: PlotModel } = require("../properties/plot.model");
const { createAuditLog, AuditLog } = require("../administration/auditLog.model");
const { canTransition } = require("../properties/stateMachine");
const ApiError = require("../../utils/ApiError");
const NotificationService = require("../notifications/service");
const InvoiceService = require("../invoices/service");

const updateStage = (stages, name, actor, status, remarks) => stages.map((stage) => stage.stage === name ? { ...stage, status, approver: actor, actedAt: new Date().toISOString(), remarks } : stage);
class PossessionService {
  static async enrich(application) { const [member, plot] = await Promise.all([Member.findById(application.member), Plot.findById(application.plot)]); return { ...application, memberRef: member, plotRef: plot }; }
  static async list({ status, page = 1, limit = 20 }) { const all = await PossessionApplication.find(status ? { status } : {}, { sort: { createdAt: -1 } }); const p = Number(page) || 1; const l = Number(limit) || 20; return { data: await Promise.all(all.slice((p - 1) * l, p * l).map((item) => this.enrich(item))), pagination: { page: p, limit: l, total: all.length, pages: Math.ceil(all.length / l) } }; }
  static async get(id) { const item = await PossessionApplication.findById(id); if (!item) throw new ApiError(404, "Possession application not found"); return this.enrich(item); }
  static async create(data, req) { if (!(await Member.findById(data.member))) throw new ApiError(400, "Member not found"); const plot = await Plot.findById(data.plot); if (!plot) throw new ApiError(400, "Plot not found"); if (plot.currentOwner !== data.member) throw new ApiError(409, "Member is not the current plot owner"); const application = await PossessionApplication.create({ ...data, possessionCharges: Number(data.possessionCharges) }, req.user._id); await createAuditLog({ req, entityType: "PossessionApplication", entityId: application._id, action: AuditLog.ACTIONS.CREATE, changes: { after: application } }); return this.enrich(application); }
  static async verify(id, req) { const app = await PossessionApplication.findById(id); if (!app) throw new ApiError(404, "Possession application not found"); const plot = await Plot.findById(app.plot); if (!plot || plot.currentOwner !== app.member) throw new ApiError(409, "Eligibility verification failed: member does not own this plot"); const installments = await Installment.find({ member: app.member }); const dues = installments.filter((item) => item.plot === app.plot && Number(item.balance) > 0).reduce((sum, item) => sum + Number(item.balance), 0); if (dues > 0) throw new ApiError(409, `Outstanding dues of ${dues} block possession`); const readiness = [PlotModel.STATUS.ALLOTTED, PlotModel.STATUS.SOLD, PlotModel.STATUS.TRANSFERRED, PlotModel.STATUS.CONSTRUCTED, PlotModel.STATUS.UNDER_CONSTRUCTION].includes(plot.status); if (!readiness) throw new ApiError(409, `Plot site is not ready for possession from status ${plot.status}`); await PossessionApplication.update(id, { status: PossessionApplication.STATUS.UNDER_VERIFICATION, eligibilityVerified: true, duesVerified: true, siteReadinessVerified: true, outstandingDues: 0, approvalStages: updateStage(app.approvalStages, "Verification", req.user._id, "Completed", "Eligibility, dues, and site readiness verified") }); return this.get(id); }
  static async payCharges(id, req) { const app = await PossessionApplication.findById(id); if (!app) throw new ApiError(404, "Possession application not found"); if (app.status !== PossessionApplication.STATUS.UNDER_VERIFICATION) throw new ApiError(409, "Possession is not ready for charge payment"); await PossessionApplication.update(id, { chargesPaid: true, chargesPaidAt: new Date().toISOString(), approvalStages: updateStage(app.approvalStages, "Charges", req.user._id, "Completed", "Possession charges paid") }); return this.get(id); }
  static async approve(id, req) { const app = await PossessionApplication.findById(id); if (!app) throw new ApiError(404, "Possession application not found"); if (!app.eligibilityVerified || !app.duesVerified || !app.siteReadinessVerified || !app.chargesPaid) throw new ApiError(409, "Eligibility, dues, site readiness, and charges must be cleared before approval"); await PossessionApplication.update(id, { status: PossessionApplication.STATUS.APPROVED, approvalStages: updateStage(app.approvalStages, "Approval", req.user._id, "Completed", "Possession approved") }); await NotificationService.safeNotifyMember(app.member, { title: "Possession application approved", message: "Your possession application has been approved.", relatedEntityType: "PossessionApplication", relatedEntityId: id, eventType: "possession.approved", eventKey: `possession-approved:${id}` }); return this.get(id); }
  static async issue(id, req) { const app = await PossessionApplication.findById(id); if (!app) throw new ApiError(404, "Possession application not found"); if (app.status !== PossessionApplication.STATUS.APPROVED || !app.chargesPaid) throw new ApiError(409, "Only approved applications with paid charges can be issued"); const plot = await Plot.findById(app.plot); if (!canTransition(plot.status, PlotModel.STATUS.POSSESSED)) throw new ApiError(409, `Plot cannot move from ${plot.status} to Possessed`); const handoverDate = new Date().toISOString(); await Plot.update(app.plot, { status: PlotModel.STATUS.POSSESSED }); await PossessionApplication.update(id, { status: PossessionApplication.STATUS.POSSESSED, handoverDate, possessionLetterUrl: `/api/possession/${id}/letter.pdf`, approvalStages: updateStage(app.approvalStages, "Possession", req.user._id, "Completed", "Possession letter issued") }); await createAuditLog({ req, entityType: "PossessionApplication", entityId: id, action: AuditLog.ACTIONS.UPDATE, changes: { before: app, after: { status: PossessionApplication.STATUS.POSSESSED, handoverDate } } }); await NotificationService.safeNotifyMember(app.member, { title: "Possession issued", message: `Possession has been issued for plot ${plot.plotNumber}.`, relatedEntityType: "PossessionApplication", relatedEntityId: id, eventType: "possession.issued", eventKey: `possession-issued:${id}` }); const issued = await this.get(id); await InvoiceService.safeRegisterInvoice("Possession", issued, { fileUrl: issued.possessionLetterUrl || `/api/possession/${id}/letter.pdf`, createdBy: req.user._id }); return issued; }
  static async letter(id) { const app = await this.get(id); if (app.status !== PossessionApplication.STATUS.POSSESSED) throw new ApiError(409, "Possession must be issued before downloading the letter"); return new Promise((resolve) => { const chunks = []; const pdf = new PDFDocument({ margin: 50 }); pdf.on("data", (chunk) => chunks.push(chunk)); pdf.on("end", () => resolve({ app, buffer: Buffer.concat(chunks) })); pdf.fontSize(20).text("Housing Society Possession Letter", { align: "center" }).moveDown().fontSize(12).text(`Member: ${app.memberRef?.name || app.member}`).text(`Plot: ${app.plotRef?.plotNumber || app.plot}`).text(`Handover date: ${new Date(app.handoverDate).toLocaleString()}`).text(`Utilities - Electricity: ${app.utilities?.electricity || "—"}, Gas: ${app.utilities?.gas || "—"}, Water: ${app.utilities?.water || "—"}`).moveDown().text("The above plot has been handed over for possession.").end(); }); }
}
module.exports = PossessionService;